matrix:
  include:
  - language: python
    python: 2.7
    before_script:
    - cd .
    - pwd
    script:
    - pytest

  - language: java
    jdk:
    - oraclejdk8
    - openjdk8
    - openjdk7
    - oraclejdk7
    before_script:
    script:
    - mvn test


notifications:
  email:
  - yishenggudou@gmail.com